version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - "3000:3000"
    #volumes:
    #  - ./app:/app
    #  - ./common:/common
    #command: npm run dev

  backend:
    build:
      #context: ./server
      dockerfile: ./dockerfile-server
    ports:
      - "9000:9000"
    #volumes:
    #  - ../server:../server
    #  - ../common:../common
    #working_dir: /server
    #command: npm run dev
